'use client';

import './globals.css';
import React, { useMemo, useState } from 'react';
import Header from '@/components/Header/Header';
import Dots from '@/components/Dots/Dots';
import PagesContext from '@/contexts/pagesContext';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  const [activePage, setActivePage] = useState(0);

  const pagesContextValue = useMemo(() => {
    return {
      activePage,
      setActivePage,
    };
  }, [activePage]);

  return (
    <html lang="en">
      <body>
        <PagesContext.Provider value={pagesContextValue}>
          <Header />
          <main>
            <Dots />
            {children}
          </main>
        </PagesContext.Provider>
      </body>
    </html>
  );
};

export default RootLayout;
